# Generated by Django 4.1.5 on 2023-06-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilisateur',
            table='website_utilisateur',
        ),
    ]
